### PR TITLE
Fix Vision

### PR DESCRIPTION
**Pull request by ciaran-regan-ie**
Fixes the vision so that objects are hidden behind walls. The agent must get within 4 blocks of the object in one of the cardinal directions (up down left right) to become visible.

### CODE REVIEW

**Comment by ciaran-regan-ie** [comment]
https://github.com/ConnectSphereInc/Plinf.jl/assets/82412948/6028da18-7492-4a61-8359-c9aa93d97c01

https://github.com/ConnectSphereInc/Plinf.jl/assets/82412948/5b20e601-72e0-4064-88a2-a95dea8abf49

**Comment by ciaran-regan-ie** [comment]
@krmr73 Do you think this is okay to merge?

**Comment by krmr73** [comment]
@ciaran-regan-ie Great work!!
One thing that bothers me is that objects don't disappear from vision.

An example of the results of the search method being implemented in my branch would as follows.
The result of this vision is a bit odd? (it is possibly a bug in my implementation is affecting this.)

https://github.com/ConnectSphereInc/Plinf.jl/assets/88866882/b3d74a03-c05b-4c8b-94e7-8e46c2b0c5c3

**Comment by ciaran-regan-ie** [comment]
@krmr73 I think objects remaining in vision is fine for now. We can consider it as the agent 'remembering' where everything is.

About the video, It looks like you found a bug - nice! 

I will try to fix it.

**Comment by ciaran-regan-ie** [comment]
@krmr73 I have pushed a potential fix. Could you please check again if its working? Id like to see the video again just to make sure!

**Comment by krmr73** [comment]
@ciaran-regan-ie Thank you for quick fixing! The same situation could not be reproduced because it has randomness. I tried several times and these results look good!

https://github.com/ConnectSphereInc/Plinf.jl/assets/88866882/900830e3-2dcd-4332-8667-9c4af8fcd979

**Comment by ciaran-regan-ie** [comment]
@krmr73 ありがとうございます！

**Pull request merged**
