### PR TITLE
Update Vision

### PR DESCRIPTION
**Pull request by krmr73**
### Changes
I gave the agent a viewing angle and changed the visible range of the agent. The visible area is the red area in the following figure. 
IMG_5BB61F112B73-1

### What I want you to ask
Is this enough visible range?

### CODE REVIEW

**Review by ciaran-regan-ie — CHANGES_REQUESTED** [review]
@krmr73 Great work! Updating the vision is not easy! 

However, I've been testing out different trajectories and I noticed a problem. See this clip: 

https://github.com/user-attachments/assets/63ad9e88-05c6-4eb6-9671-2ef132c3b67b

At around halfway, the agent moves right and can see the carrot through the wall. This means there is some slight problem with the if/and statements. 

To solve this issue, I recommend you try to replicate this trajectory, with the agent moving right and seeing through that wall.

**Comment by ciaran-regan-ie** [comment]
@krmr73 I think this vision range is enough!

**Comment by krmr73** [comment]
@ciaran-regan-ie Thank you for finding the bug! In the case of diagonals, the agent was able to see objects. I'm going to fix it.

**Comment by ciaran-regan-ie** [comment]
@krmr73 Thanks so much!

**Comment by krmr73** [comment]
@ciaran-regan-ie I fixed the problem objects diagonally forward through the wall are visible. Please check this fix.

**Comment by ciaran-regan-ie** [comment]
@krmr73 Nice work! LGTM!

**Pull request merged**
